data_params:
  train_year: '2008'
  valid_year: '2009'

model_params:
  name: Linear
  input_dim: 8

loss: MSELoss
optimizer: Adam
scheduler:
  name: StepLR
  step_size: 30
  gamma: 0.1

training_params:
  num_epochs: 1
  learning_rate: 0.001
  batch_size: 8192
  gradient_clipping: 1.0
  early_stopping_patience: 5
